//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingDetail
    {
        public int MeetingDetailId { get; set; }
        public int MeetingId { get; set; }
        public string Attendee { get; set; }
    
        public virtual Meeting Meeting { get; set; }
    }
}
